name: MASTER PUSH

on:
  push:
    branches: [ workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
      
    steps:
    - name: setup actions
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Initialize db, start docker-compose and test frontend, backend and e2e
      run: |
        echo ${{ secrets.ENV }} > .env
        echo ${{ secrets.ENV }} > ./scripts/populate/.env
        cd frontend
        npm install
        npm test