name: MASTER PUSH

on:
  push:
    branches: [ workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
      
    steps:
    - name: setup actions
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install, initialize db and test
      run: |
        echo ${{ secrets.ENV }} > .env
        npm install
        cd frontend
        npm install
        cd ../backend
        npm install
        cd ..
        docker-compose up -d vaccine-exercise-db
        sleep 30
        docker exec -u postgres vaccine-exercise-db psql -c "DROP DATABASE \"vaccine_db\""
        docker exec -u postgres vaccine-exercise-db psql -c "CREATE DATABASE \"vaccine_db\""
        sh ./scripts/convertDataToJson.sh
        DB_HOST=localhost node ./scripts/populate/populate.js
        docker-compose up -d
        cd backend
        npm test
        cd ../frontend
        npm test
        cd ..
        npm run test:e2e